server:
  port: 5324
spring:
  application:
    name: family-member
  cloud:
    nacos:
      server-addr: 192.168.209.161:8848
      discovery:
        namespace: bc683702-411f-4d22-8668-9a202045c7c4
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.209.161:3306/docker?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.209.161
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
#mybatis日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#请求处理的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
#分布式事务seata配置
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.209.161:8848
      namespace: bc683702-411f-4d22-8668-9a202045c7c4
      group: DEFAULT_GROUP  #组
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: seata-dome  #事务组
  service:
    vgroup-mapping:
      seata-dome: GS
  #开启数据源代理的XA模式
  data-source-proxy-mode: XA


