server:
  port: 4314
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/familymember?
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲时间
        min-idle: 0 #最小连接数
        max-wait: 100 #连接等待时间
  #发件人邮箱服务配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 2726118282@qq.com
    password: xiuxkjlltohjdgjb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  #json格式日期转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#指定mybatis映射文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #控制台打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

